### PR TITLE
No longer automatically add resources dir to $PATH

### PR DESCRIPTION
**Pull request by rcannood**
Changes:
* `Functionality`: The resources dir no longer automatically added to the PATH variable. 
  To alter this behaviour, set `.functionality.add_resources_to_path` to `true`.

@tverbeiren is this ok with you? I set it such that for unit tests, the resources dir _is_ still added to the PATH, but by default this is set to false for other components. Do you expect this change to affect anything in your code?

### CODE REVIEW

**Comment by rcannood** [comment]
Kind reminder -- is this ok for you @tverbeiren ?

**Comment by tverbeiren** [comment]
Ok!
Should be added to the docs, though.

**Comment by BlackDragonBE** [comment]
@tverbeiren I've added this change to my docs TODO list.

**Comment by rcannood** [comment]
Thanks all! :relaxed:

**Pull request merged**
