### PR TITLE
Add `--dry_run` to `viash [ns] test` for generating test scripts

### PR DESCRIPTION
**Pull request by tverbeiren**
## Describe your changes

During CI runs, we need the ability to split generating the test files and running them. This argument generates the test scripts.

## Type of Change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New functionality (non-breaking change which adds functionality)
- [ ] Major change (non-breaking change which modifies existing functionality)
- [ ] Minor change (non-breaking change which does not modify existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist

Requirements:

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc.
- [ ] I have performed a self-review of my code by checking the "Changed Files" tab.
- [ ] My code follows the code style of this project.

Tests:

- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

Documentation:

- [ ] Proposed changes are described in the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tverbeiren** [comment]
To try this out:

```
docker run -v $PWD:/tmp/workdir -e VIASH_TEMP=/tmp/workdir/ \
  -it ghcr.io/viash-io/viash:generate_tests \
  viash ns test --src /tmp/workdir/src --keep true \
  --dry_run --engine native -c '.engines += { type: "native" }'
```

**Comment by Grifs** [comment]
Code itself looks good to me, however I have a few concerns about the viability:
- setting the `--src` folder: 
  - This makes us miss the package config which might contain valuable information
  - This also makes that we don't have a valid project root, (important for e.g. merge)
  - The `.../src` folder is configurable. Unless the CI will require that this field is set to `src`, but could be considered to arbitrarily restrictive as long as the `src` is configurable in the package config
- This won't work for older versions of Viash (so nothing under `0.9.0` will ever be able to run on the CI). If so required we should backport this to Viash `0.8.x`. While still required to be a recent version of `0.8`, the migration should be much easier.
- (Minor) If the output will ever be parsed, adding `--colorize false` to the given example command might make things much easier

**Comment by tverbeiren** [comment]
> * setting the `--src` folder:
>   
>   * This makes us miss the package config which might contain valuable information
>   * This also makes that we don't have a valid project root, (important for e.g. merge)
>   * The `.../src` folder is configurable. Unless the CI will require that this field is set to `src`, but could be considered to arbitrarily restrictive as long as the `src` is configurable in the package config

Good points!

This is related to another issue I encountered some time ago in the CI: The Viash config schema is potentially updated with each version but so is the CLI. The same here. The only options I see, are 1) to backport the functionality to older versions of Viash and 2) to remove functionality from the CI for older versions. And that's exactly your next point:

> * This won't work for older versions of Viash (so nothing under `0.9.0` will ever be able to run on the CI). If so required we should backport this to Viash `0.8.x`. While still required to be a recent version of `0.8`, the migration should be much easier.

Although this sounds bad, we should keep in mind that existing projects already contain releases that should not be rebuilt anyway.

**Comment by Grifs** [comment]
Right, if we'd want to "backport" this to Viash 0.8, then our normal MO is to write the feature/fix on the `develop_0_8` branch and then "forward port".

Also, regardless if we'll merge this into `develop` or `develop_0_8` first, could you add an entry in the changelog?

**Comment by Grifs** [comment]
Note from Toni: It would be great to have an option to disable the randomized output folder name and instead have deterministic behaviour

**Comment by Grifs** [comment]
Changes were backported to `develop_0_8` in #676 and then `develop_0_8` was merged into `develop`.

**Pull request closed without merging**
