### PR TITLE
DockerPlatform: Add `target_platform` parameter.

### PR DESCRIPTION
**Pull request by DriesSchaumont**
## Describe your changes

`DockerPlatform`: add `target_platform` parameter to the docker platform config to enable multi-plaform builds.

## Issue ticket number and link
~Closes #xxxx (Replace xxxx with the GitHub issue number)~

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [ ] Relevant unit tests have been added

### CODE REVIEW

**Review by rcannood — COMMENTED** [review]
Minor comments. Let me know when I need to review :)

**Comment by rcannood** [comment]
Ping @DriesSchaumont

**Comment by DriesSchaumont** [comment]
I recently learned more about how multi-platform images can be build using `buildx`. Basically, there are three [options](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images):

1. Building on multiple native nodes
2. Using a stage in Dockerfile to cross-compile to different architectures
3. Using emulation of a the different build options (uses QEMU) 

Number 1 is hard to do because it needs specific configuration and setup of the builder instance (basically: 1 builder instance connected to multiple nodes over a network). 

Number 2 is only applicable to software projects that allow a user to configure cross-compilation in an easy manner. 

Number 3 is the most generic: it is fairly easy to setup, (`docker run --privileged --rm tonistiigi/binfmt --install all`), and can be used to build the images from a single system. However, as described [here](https://docs.docker.com/build/drivers/docker-container/#qemu): "_QEMU performs full-system emulation of non-native platforms, which is much slower than native builds. Compute-heavy tasks like compilation and compression/decompression will likely take a large performance hit._". It has the advantage that many pieces of software can be compiled by auto-detecting the native platform, so configuration is generally easier.

I tried option 3, but was hit with an issue at the end of a successful  build: 

`WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load`.

It seems when using `--builder=container`, build artifacts must be explicitly loaded into the local image store using `--load`. This means that if `--load` is not specified, `docker run` will not work because docker cannot find the image. 

However, when using `--load`, I was hit with `ERROR: docker exporter does not currently support exporting manifest lists` see ([this](https://github.com/docker/roadmap/issues/371)). It seems that storing multi-platform images, the `containerd` image store can be used. It can be enabled by adding:

```json
"features": {
    "containerd-snapshotter": true
}
```

to the dockerd configuration (`/etc/docker/daemon.json`). See https://docs.docker.com/storage/containerd/
This enabled to store OCI compliant images using `--load`

Alternatively (as a workaround), the image for a single platform at a time be loaded into the container store 
```
# build both images
docker buildx build --platform linux/arm64,linux/amd64 .
# load just one platform
docker buildx build --load --platform linux/amd64 -t my-image-tag .
# optionally load another platform with a different tag
docker buildx build --load --platform linux/arm64 -t my-image-tag:arm64 .
# push both platforms as one image manifest list
docker buildx build --push --platform linux/arm64,linux/amd64 -t docker.palantir.build/publish:tag .
```

**Comment by DriesSchaumont** [comment]
This PR has become stale. While I think its an interesting concept, there are too many questions needing answers :)

**Pull request closed without merging**
