### PR TITLE
Remove legacy nextflow code

### PR DESCRIPTION
**Pull request by rcannood**
## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Does this PR contain:
  - [x] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] Relevant unit tests have been ~added~ removed ;)

### CODE REVIEW

**Comment by Grifs** [comment]
This will effectively remove any and all documentation on the website about the legacy nextflow platform. Is that desired?

**Comment by rcannood** [comment]
Fine by me ^^ @tverbeiren do you know someone who is still using legacy Nextflow?

**Comment by tverbeiren** [comment]
It's fine to remove legacy Nextflow platform documentation. We can always retrieve markdown/qmd versions from the repo if needed.

**Comment by rcannood** [comment]
Woohoow! :partying_face:

**Pull request merged**
