### PR TITLE
Improve error reporting to the user in some cases where files or fold…

### PR DESCRIPTION
**Pull request by Grifs**
…ers can't be found.

Depending on the thrown exception, more or less context was given.

### CODE REVIEW

**Comment by rcannood** [comment]
Is this a solution to the following?

```bash
mkdir foo
cd foo
viash ns list
```

    foo

**Comment by rcannood** [comment]
Would you mind adding a unit test? :bow:

**Comment by Grifs** [comment]
yes, but actually no. ;)

The exact scenario would be
```
mkdir foo
cd foo
viash ns list --src bar
```

```
bar
```

or without the recent code change regarding the `src` folder:
```
mkdir foo
cd foo
viash ns list
```

```
src
```

**Comment by rcannood** [comment]
Of course, you're right! So this pr solved that issue?

**Comment by Grifs** [comment]
It should, yes.

**Review by rcannood — APPROVED** [review]

**Pull request merged**
